export const SET_LABEL = 'setLabel'
export const SET_MESSAGE = 'setMessage'
export const SET_COLOR = 'setColor'
export const SET_URL = 'setUrl'
export const SET_LOGS = 'setLogs'
export const SET_LOG_COUNT = 'setLogCount'
export const SET_BASE64 = 'setBase64'
